### PR TITLE
use pcap ts instead of urb time for sleeps, fix vidpid filter bug

### PR DESCRIPTION
**Pull request by JohnDMcMaster**
Experimental, test a little more before merging

Fixes https://github.com/JohnDMcMaster/usbrply/issues/40

Fixes https://github.com/JohnDMcMaster/usbrply/issues/59

### CODE REVIEW

**Comment by worldjoe** [comment]
I'm not sure how to get this to work on my Windows box. But don't mind me if this is tested and working for you. I pulled down this branch and bumped the version to 2.1.2 just so I could ensure I was testing the branched code.

`usbrply --wrapper --vid 0x10c4 --pid 0xea60 --device-hi -p C:\Users\trave\Documents\singularity.pcapng > singlularity_winsleep.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\usbrply-script.py", line 33, in <module>
    sys.exit(load_entry_point('usbrply==2.1.2', 'console_scripts', 'usbrply')())
  File "C:\ProgramData\Anaconda3\lib\site-packages\usbrply-2.1.2-py3.8.egg\usbrply\main.py", line 134, in main
  File "C:\ProgramData\Anaconda3\lib\site-packages\usbrply-2.1.2-py3.8.egg\usbrply\printers.py", line 14, in run
  File "C:\ProgramData\Anaconda3\lib\site-packages\usbrply-2.1.2-py3.8.egg\usbrply\pyprinter.py", line 250, in run
Exception: Failed to guess vid/pid: found 0 device entries`

I also tried putting quotes around the vid and pid parameters. I even tried editing pyprinter.py
`        # FIXME
        self.vid = 0x10c4
        self.pid = 0xea60`
But I always get the same error.

To install I edited setup.py to version 2.1.2 and ran `python setup.py install`

**Comment by worldjoe** [comment]
I got past the generation problem. Not sure what I did wrong before. But I'm able to generate a successful python script using this branch from my original pcapng file.

I'm diffing the output from master with the output from this match and there doesn't appear to be any non white space differences. I am guessing here, but I suspect my problem is the software that communicates to my USB device isn't doing any sleep calls. I am guessing the software I am capturing from is handling the timing of the events internally and emitting USB commands at set intervals. So I would need to have usbrply grab the timing from the pcapng and emit sleep statements in python to emulate the same timing of the events emitted during the pcapng.
[testcase.zip](https://github.com/JohnDMcMaster/usbrply/files/7919253/testcase.zip)

For background, my use case is I have a Windows piece of software that communicates with a USB connected LED controller. The software plays back about 10 minutes of a light show to the USB device. When I capture the commands via wincap I get the pcapng file and I convert using usbrply, but when I playback the commands the entire 10 minute light show is essentially compressed into 20 seconds or so. I've attached my pcapng file and output from this branch.

**Comment by worldjoe** [comment]
I think what I was hoping that the "time" data from the pcapng file could be used to control when to send messages to the usb device. But instead all the messages are just sent one after another and my USB device can't buffer them so they light show starts stepping over itself - attempting to display multiple segments at the same time and ending after just about 1 minute or less.

Given that my light show is supposed to be 10 minutes long I added a python time.sleep() call inside the controlWrite and bulkWrite methods. I divided the number of write calls into the 10 minute length and came up with a sleep of 2.3904 seconds. But looking at the numerous reads from the USB device it makes me wonder if the software is using the response from the read calls to determine when to send the next write command because the USB device really isn't reporting anything useful back to the PC since the USB device has no data gathering systems (it only controls lights). For now the sleeps are kind of working. I'll play around with this for a bit to see if I can figure out the frequency I'm supposed to be doing write commands to the device.

**Comment by JohnDMcMaster** [comment]
Hi,
I can't take a detailed look at this right now but real quick: did you try --sleep? There is supposed to be a mode where it adds sleeps exactly for use cases like yours

```
  --sleep               Insert sleep statements between packets to keep original timing
```

**Comment by worldjoe** [comment]
I did not try sleep! Thanks. Also no worries, I don't expect you to debug my use case.

**Comment by JohnDMcMaster** [comment]
Trying to sort out the general state of things. Seems like this branch generally improves upon master so I'm going to merge it in and work on remaining bugs from there.

**Pull request merged**
